### ISSUE TITLE
For loop inside VStack?

### ISSUE THREAD

**Issue by BayramInanc** [FluidGroup/MondrianLayout#76]
Can we use for in loop inside vstack or hstack?

**Comment by muukii** [comment]
@BayramInanc 
you want to do like this?

```swift
VStackBlock {
  for view in views {
    view.viewBlock.height(10)
  }
}
```

**Comment by BayramInanc** [comment]
Yes, but do we have to use height in this case? Can we use only view itself in for loop?

**Comment by muukii** [comment]
ah, nono
it's just an example code.
the point is using `for` loop

**Comment by BayramInanc** [comment]
Yes ı want to use like this. Btw, The library is the best in github. I searched and used lots of autolayout dsl but this is so much efficient qnd different thanks a lot
